Condorcar/Controllers/RideController.cs
using Condorcar.Models.POCO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Condorcar.Controllers
{
    public class RideController : Controller
    {

        /////////////////////////////////////////////////////////////////////////////////
        ///                               Index                                       ///
        /////////////////////////////////////////////////////////////////////////////////
        ///                 Affiche la liste des trajets du véhicule                 ////
        public ActionResult Index()
        {
            if (!(Session["User"] is CDriver)) return Redirect("../Home/Index");
            Session["persoRides"] = CRide.GetAllOfDay((CDriver)Session["User"]); ;
            return View();
        }

        /////////////////////////////////////////////////////////////////////////////////
        ///                               History                                     ///
        /////////////////////////////////////////////////////////////////////////////////
        ///                 Affiche la liste des trajets du véhicule                 ////
        public ActionResult AllPersonalRide()
        {
            if (!(Session["User"] is CDriver)) return Redirect("../Home/Index");
            Session["persoRides"] = CRide.GetAll((CDriver)Session["User"]); ;
            return View("Index");
        }

        /////////////////////////////////////////////////////////////////////////////////
        ///                               Details                                     ///
        /////////////////////////////////////////////////////////////////////////////////
        ///                      Affiche le détail d'un trajet                       ////
        public ActionResult Details(int id)
        {
            CRide ride = new CRide();
            ride = ride.GetRide(id);
            return View(ride);
        }

        /////////////////////////////////////////////////////////////////////////////////
        ///                               Create                                      ///
        /////////////////////////////////////////////////////////////////////////////////
        ///            Ajoute un nouveau trajet dans la liste des trajets            ////
        public ActionResult Create()
        {
            if (!(Session["User"] is CDriver)) return Redirect("../Home/Index");
            CDriver user = new CDriver();
            user = (CDriver)Session["User"];    // On charge les variables du conducteur dans user
            if (user.Vehicles == null)
            {
                ViewBag.Message = "Vous n'avez aucun véhicule pour proposer un trajet !";
                return View("Index");
            }
            Session["listVehicle"] = ToSelectList(user.Vehicles); // On stock dans une session ainsi si il y a une erreur dans le formulaire, la liste de se vide pas
            return View();
        }
        
        [HttpPost]
        public ActionResult Create(CRide ride)
        {
            if (!(Session["User"] is CDriver)) return Redirect("../Home/Index");
            ride.Vehicle = CVehicle.GetVehicle(Int32.Parse(ride.VehicleId));
            if (DateTime.Compare(ride.DepartureTime, DateTime.Now) < 0)
            {
                ViewBag.Message = "Il est trop tard pour ajouter un trajet !";
                return View("Create");
            }
            if (DateTime.Compare(ride.DepartureTime, ride.ArrivalTime) > 0)
            {
                if (ride.Vehicle.Model.ToString() != "Delorean DMC12")
                {
                    ViewBag.Message = "Tu ne voyages pas dans le temps il me semble !";
                    return View("Create");
                }
            }
            
            CDriver driver = new CDriver();
            driver = (CDriver)Session["User"];    // On charge les variables du conducteur dans user
            ride.Driver = driver; 
            ride.AddRide();
            Session["persoRides"] = CRide.GetAll((CDriver)Session["User"]); ;
            ViewBag.Message = "Vous avez bien enregistré un nouveau trajet";
            return View("Index");
        }

        /////////////////////////////////////////////////////////////////////////////////
        ///                               History                                     ///
        /////////////////////////////////////////////////////////////////////////////////
        ///                     Affiche la liste de tous les trajets                 ////
        public ActionResult History()
        {
            if (!(Session["User"] is CPassenger)) return Redirect("../Home/Index");
            CPassenger user = new CPassenger();
            user = (CPassenger)Session["User"];
            Session["smoker"] = user.Smoker;
            Session["userRideList"] = user.RideList;
            Session["rideList"] = CRide.GetAll();
            return View("List");
        }

        /////////////////////////////////////////////////////////////////////////////////
        ///                               List                                        ///
        /////////////////////////////////////////////////////////////////////////////////
        ///                     Affiche la liste de tous les trajets d'ajd           ////
        public ActionResult List()
        {
            if (!(Session["User"] is CPassenger)) return Redirect("../Home/Index");
            CPassenger user = new CPassenger();
            user = (CPassenger)Session["User"];
            Session["smoker"] = user.Smoker;
            Session["userRideList"] = user.RideList;
            Session["rideList"] = CRide.GetAllOfDay();
            return View();
        }

        /////////////////////////////////////////////////////////////////////////////////
        ///                               UnSubscribe                                 ///
        /////////////////////////////////////////////////////////////////////////////////
        ///                     Retire un passager à un trajet                       ////
        public ActionResult UnSubscribe(int idRide)
        {
            if (!(Session["User"] is CPassenger)) return Redirect("../Home/Index");
            CPassenger passenger = (CPassenger)Session["User"];
            CRide ride = new CRide();
            ride = ride.GetRide(idRide);
            passenger.RemoveToRide(ride);
            Session["User"] = passenger;
            ViewBag.Message = "Vous vous êtes bien Désinscris du trajet !";
            Session["smoker"] = passenger.Smoker;
            Session["userRideList"] = passenger.RideList;
            Session["rideList"] = CRide.GetAll();
            return View("List");
        }

        /////////////////////////////////////////////////////////////////////////////////
        ///                               Subscribe                                   ///
        /////////////////////////////////////////////////////////////////////////////////
        ///                     Inscrit un passager à un trajet                      ////
        public ActionResult Subscribe(int idRide)
        {
            if (!(Session["User"] is CPassenger)) return Redirect("../Home/Index");
            CRide ride = new CRide();
            ride = ride.GetRide(idRide);
            if (ride.Vehicle.Seat > ride.Passengers.Count()) // Si la liste des passager n'est pas complet 
            {
               if(DateTime.Compare(ride.ArrivalTime.Date, DateTime.Now) < 0 )
               {
                    if (DateTime.Compare(ride.DepartureTime.Date, DateTime.Now.Date.AddHours(1)) < 0 )
                    {
                        CPassenger passenger = (CPassenger)Session["User"];
                        passenger.AddToRide(ride);
                        Session["User"] = passenger;
                        ViewBag.Message ="Vous vous êtes bien inscrit au trajet ! ID: " + idRide + "()" +ride.Id;
                        Session["smoker"] = passenger.Smoker;
                        Session["userRideList"] = passenger.RideList;
                        Session["rideList"] = CRide.GetAll();
                        return View("List");
                    }
                    else
                    {
                        ViewBag.Message = "Trop tard ! Le départ est déjà en cours ou en préparation !";
                        Session["rideList"] = CRide.GetAll();
                        return View("List");
                    }
               }
               else // Trajet est déjà fini
               {
                    ViewBag.Message = "Trop tard ! Le trajet est déjà fini !";
                    Session["rideList"] = CRide.GetAll();// TODO: catalogue
                    return View("List");
               }
            }
            else // Sinon le nombre de place est atteins !
            {
                ViewBag.Message = "Nombre de place maximum atteinte !";
                Session["rideList"] = CRide.GetAll();// TODO: catalogue
                return View("List");
            }
        }

        /////////////////////////////////////////////////////////////////////////////////
        ///                               Delete                                      ///
        /////////////////////////////////////////////////////////////////////////////////
        ///                 Supprime un trajet dans la liste des trajets             ////
        // POST: Ride/Delete/5
        public ActionResult Delete(int id)
        {
            if (!(Session["User"] is CDriver)) return Redirect("../Home/Index");
            CRide ride = new CRide();
            ride = ride.GetRide(id);
            if(ride.Passengers.Count() > 0)
            {
                ViewBag.Message = "Impossible de supprimer ce trajet, des passagers ont déjà réservé ou le trajet est déjà terminé";
                return RedirectToAction("../Driver/Index");

Condorcar/Views/Ride/Create.cshtml
@model Condorcar.Models.POCO.CRide
@{ViewBag.Vehicles = Session["listVehicle"];}


@ViewBag.Message
@using (Html.BeginForm("Create", "Ride", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Création d'un trajet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.DepartureTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.DepartureTime, new { @class = "form-control", @type = "datetime-local" })
                @Html.ValidationMessageFor(model => model.DepartureTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ArrivalTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.ArrivalTime, new { @class = "form-control", @type = "datetime-local" })
                @Html.ValidationMessageFor(model => model.ArrivalTime, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Vehicle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(Model => Model.VehicleId, (SelectList)ViewBag.Vehicles, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vehicle, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Place, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Place, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Place, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ajouter un trajet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

   <center><button class="btn btn-danger"><img src="~/Content/image/icons8-no-alcohol-filled-50.png" /> La consommation de vin est interdite lors du trajet !</button></center> 

        <div>
            @Html.ActionLink("Retour à la liste", "Index")
        </div>

Condorcar/Views/Ride/Delete.cshtml
@model Condorcar.Models.POCO.CRide

<h3>Êtes vous certain de vouloir le supprimer ?</h3>
<div>
    <h4>CRide</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DepartureTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArrivalTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Place)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Place)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Suppression" class="btn btn-default" />
        </div>
    }
</div>

Condorcar/Views/Ride/Details.cshtml
@model Condorcar.Models.POCO.CRide
@using Condorcar.Models.POCO
<div>
    <h4>Détail du trajet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DepartureTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DepartureTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ArrivalTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Place)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Place)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt>
            <picture>Pseudo du conducteur</picture>
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Driver.Pseudo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Vehicle.Model)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Vehicle.Model)
        </dd>
        @*<dt> // La liste ne s'affiche pas, à regarder plus tard
            <picture>Liste des passagers</picture>
        </dt>
        <dd>
                  if(Model.Passengers != null)
                  {
                      foreach (var passenger in (List<CPassenger>)Model.Passengers)
                      {
                          <p>1</p>
                          @Html.Display(passenger.Pseudo)
                      }
                  }
                  else { <p>Aucun passager dans ce trajet !</p>}
         </dd>*@
    </dl>
        </div>

Condorcar/Views/Ride/Index.cshtml
@model IEnumerable<Condorcar.Models.POCO.CRide>
@{ ViewBag.Rides = Session["persoRides"];}
@using Condorcar.Models.POCO;
<p>
    <button onclick="location.href='@Url.Action("Create", "Ride")'" style="background-color:transparent; border-color:transparent;"><img src="~/Content/image/icons8-carpool-filled-50.png" /><br />Ajouter un nouveau trajet</button>
</p>
<p>@ViewBag.Message</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DepartureTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Place)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vehicle.Seat)
        </th>
        <th></th>
    </tr>
    @if (ViewBag.Rides != null)
    {
        foreach (var item in (List<CRide>)ViewBag.Rides)
        {
            @*Incompréhension lié au retour dans le temps pour la delorean  V *@
            if (DateTime.Compare(item.ArrivalTime, DateTime.Now) < 0 && DateTime.Compare(item.DepartureTime, DateTime.Now) < 0)
            { ViewBag.Colour = "#e84e4e"; }
            else if (DateTime.Compare(item.DepartureTime, DateTime.Now) < 0)
            {
                if (DateTime.Compare(item.ArrivalTime, DateTime.Now) > 0)
                {
                    ViewBag.Colour = "#417ee0";
                }
            }
            else
            {
                ViewBag.Colour = "#4ee872";
                ViewBag.Subscribable = true;
            }
            <tr style="background-color:@ViewBag.Colour">
                <td>
                    @item.DepartureTime
                </td>
                <td>
                    @item.ArrivalTime
                </td>
                <td>
                    @item.Place
                </td>
                <td>
                    @item.Price €
                </td>
                <td>
                    @item.Vehicle.Seat
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @if (DateTime.Compare(item.DepartureTime, DateTime.Now) > 0)
                    {@Html.ActionLink("Supprimer", "Delete", new { id = item.Id })}
                </td>
            </tr>
        }
        <tr>
            <td></td> <td></td>
            <td style="background-color:#e84e4e">Le trajet est fini.</td>
            <td style="background-color:#417ee0">Le trajet est en cours.</td>
            <td style="background-color:#4ee872">Le trajet est disponible.</td>
            <td></td>
        </tr>
     }


    </table>

Condorcar/Views/Ride/List.cshtml
@using Condorcar.Models.POCO;

@model IEnumerable<Condorcar.Models.POCO.CRide>
@{ ViewBag.RideList = Session["rideList"];
    ViewBag.Smoker = Session["smoker"];
    ViewBag.UserRideList = Session["userRideList"];}


@ViewBag.Message
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DepartureTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ArrivalTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Place)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Driver.Pseudo)
        </th>
        <th>
            <p>Passagé(s)/Place(s) Maximum</p>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Vehicle.CanSmoke)
        </th>
        <th></th>
    </tr>
    @if (ViewBag.RideList != null)
    {
        foreach (var item in (List<CRide>)ViewBag.RideList)
        {
            ViewBag.Unsuscribable = false;
            ViewBag.Subscribable = false;
            if (ViewBag.UserRideList != null)
            {
                foreach (var ride in (List<CRide>)ViewBag.UserRideList)
                {
                    if (ride.Id == item.Id)
                    {
                        ViewBag.Colour = "#7d8984";
                        ViewBag.Unsuscribable = true;
                    }
                }
            }
            if (ViewBag.Unsuscribable == false)
            {
                @*Incompréhension lié au retour dans le temps pour la delorean  V *@
                if (DateTime.Compare(item.ArrivalTime, DateTime.Now) < 0 && DateTime.Compare(item.DepartureTime, DateTime.Now) < 0)
                { ViewBag.Colour = "#e84e4e"; }
                else if (DateTime.Compare(item.DepartureTime, DateTime.Now) < 0)
                {
                    if (DateTime.Compare(item.ArrivalTime, DateTime.Now) > 0)
                    {
                        ViewBag.Colour = "#417ee0";
                    }
                }
                else
                {
                    ViewBag.Colour = "#4ee872";
                    ViewBag.Subscribable = true;
                }
            }

            <tr style="background-color:@ViewBag.Colour">
                <td>
                    @item.DepartureTime
                </td>
                <td>
                    @item.ArrivalTime
                </td>
                <td>
                    @item.Place
                </td>
                <td>
                    @item.Price €
                </td>
                <td>
                    @item.Driver.Pseudo
                </td>
                <td>
                    @item.Passengers.Count() / @item.Vehicle.Seat
                </td>
                <td>
                    @if (ViewBag.Smoker != item.Vehicle.CanSmoke)
                    {<img src="~/Content/image/smoking.png" />}
                    @if (item.Vehicle.CanSmoke)
                    {<span>Oui</span>}
                    else
                    {<span>Non</span>}

                </td>
                <td>
                    @if (ViewBag.Unsuscribable == true)
                    {
                        if (DateTime.Compare(item.DepartureTime, DateTime.Now) > 0)
                        {@Html.ActionLink("Annuler mon trajet", "UnSubscribe", new { idRide = item.Id }, new { @class = "btn btn-danger" }) }

                }
                else if (ViewBag.Subscribable)
                {

                    @Html.ActionLink("Souscrire au trajet", "Subscribe", new { idRide = item.Id }, new { @class = "btn btn-warning" })
                }
                </td>
            </tr>
        }
        <tr>
            <td></td>
            <td style="background-color:#7d8984">Vous êtes inscrit au trajet</td>
            <td style="background-color:#e84e4e">Le trajet est fini.</td>
            <td style="background-color:#417ee0">Le trajet est en cours.</td>
            <td style="background-color:#4ee872">Le trajet est disponible.</td>
            <td></td>
            <td><img src="~/Content/image/smoking.png" />@if (ViewBag.Smoker == true)
            {<p>Trajet non fumeur !!</p>}
            else
            { <p>Trajet potentiellement fumeur !!</p>} </td>
        </tr>
    }
    else
    {
        <tr><td>Il n'y a actuellement aucun trajet proposé pour les prochaines dates ! :(</td></tr>
    }
</table>