Condorcar/Controllers/VehicleController.cs
using Condorcar.Models.POCO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Condorcar.Controllers
{
    public class VehicleController : Controller
    {
        public ActionResult Index()
        {
            if (!(Session["User"] is CPassenger)) return Redirect("../Home/Index");
            return View();
        }

        /////////////////////////////////////////////////////////////////////////////////
        ///                               ManageVehicle                               ///
        /////////////////////////////////////////////////////////////////////////////////
        public ActionResult Manage() // Quand on clique sur le bouton gérer ses véhicules
        {
            if (!(Session["User"] is CDriver)) return Redirect("../Home/Index");
            ViewBag.Message = "";
            CDriver user = (CDriver)Session["User"];
            Session["vehicles"] = user.Vehicles; // On stock les véhicules du conducteur dans un Viewbag
            return View("Manage"); // On affiche la vue Manage pour gérer la liste des véhicules
        }

        /////////////////////////////////////////////////////////////////////////////////
        ///                               Delete                                      ///
        /////////////////////////////////////////////////////////////////////////////////
        ///                 Supprime un véhicule dans la liste de l'utilisateur      ////
        public ActionResult Delete(int id)
        {
            if (!(Session["User"] is CDriver)) return Redirect("../Home/Index");
            CDriver user = (CDriver)Session["User"];
            CVehicle veh = CVehicle.GetVehicle(id);
            if(!veh.ExistInAnyRide())
            {
                user.RemoveVehicle(veh);
            }
            else
            {
                ViewBag.Message = "Ce véhicule est présent dans un trajet, il ne peut donc pas être supprimé !";
                Session["vehicles"] = user.Vehicles; // On stock les véhicules du conducteur dans un Viewbag
                return View("Manage"); // On affiche la vue Manage pour gérer la liste des véhicules
            }
                
            return RedirectToAction("Manage");
        }

        /////////////////////////////////////////////////////////////////////////////////
        ///                               Add                                         ///
        /////////////////////////////////////////////////////////////////////////////////
        public ActionResult Add() // Quand on appuie sur le bouton ajouter véhicule
        {
            if (!(Session["User"] is CDriver)) return Redirect("../Home/Index");
            return View("Add"); // Formulaire d'ajout de véhicule
        }

        [HttpPost]
        public ActionResult Add(CVehicle vehicle) // Quand on valide le formulaire pour ajouter le véhicule
        {
            if (!(Session["User"] is CDriver)) return Redirect("../Home/Index");
            if (ModelState.IsValid) // Si les champs sont valides
            {
                CDriver user = (CDriver)Session["User"];    // On charge les variables du conducteur dans user
                if (user.AddVehicle(vehicle) == true) // Si il a bien pu ajouter le véhicule
                {
                    ViewBag.Message = "Vous avez enregistré un nouveau véhicule ! (Modèle : " + vehicle.Model + " places : " + vehicle.Seat + " Autorisé à fumer : " + vehicle.CanSmoke + ")";
                    Session["vehicles"] = user.Vehicles; // Pour l'afficher directe dans la liste
                    Session["User"] = user;
                    return View("Manage"); // Affichage de la liste
                }
                else // Sinon il existe déjà
                {
                    ViewBag.Vehicles = user.Vehicles; // Pour l'afficher directe dans la liste
                    ViewBag.Message = "Vous avez déjà ajouté ce véhicule parmis vos véhicules !";
                    return View("Manage"); // Affichage de la liste
                }
            }
            return View("Add"); // les champs sont pas valides
        }
    }
}

Condorcar/Views/Vehicle/Add.cshtml
@model Condorcar.Models.POCO.CVehicle

@{
    ViewBag.Title = "Ajout de véhicule";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ajout de véhicule</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Seat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Seat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Seat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CanSmoke, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.CanSmoke)
                    @Html.ValidationMessageFor(model => model.CanSmoke, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ajouter ce véhicule" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retour à la liste", "Index")
</div>

Condorcar/Views/Vehicle/Delete.cshtml
@model Condorcar.Models.POCO.CVehicle

<h3>Êtes vous certain de vouloir supprimer ce véhicule ?</h3>
<div>
    <h4>CVehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Seat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Seat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CanSmoke)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CanSmoke)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Suppression" class="btn btn-default" /> |
            @Html.ActionLink("Retour à la liste", "Index")
        </div>
    }
</div>

Condorcar/Views/Vehicle/Manage.cshtml
@{

    ViewBag.Title = "Liste des véhicules";
    ViewBag.Vehicles = Session["vehicles"];
}
@using Condorcar.Models.POCO;
@model Condorcar.Models.POCO.CVehicle
@ViewBag.Message
<h2>Liste de vos véhicules</h2>
<table>
    @{
        <tr>
            <th>Modèle du véhicule</th>
            <th>Place(s) du véhicules</th>
            <th>Autorisé à fumer</th>
        </tr>
    }

</table>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Seat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CanSmoke)
        </th>
        <th></th>
    </tr>
    @if (ViewBag.Vehicles != null)
    {
        foreach (var item in (List<CVehicle>)ViewBag.Vehicles)
        {
            <tr>
                <td>
                    @item.Seat
                </td>
                <td>
                    @item.Model
                </td>
                <td>
                    @if (item.CanSmoke)
                    {<span>Oui</span> }
                    else
                    { <span>Non</span>}
                </td>
                <td>
                    @Html.ActionLink("Supprimer", "Delete", new { id = (int)item.Id })
                </td>
            </tr>
        }
    }
    else
    {
        <tr>Vous n'avez pas encore de véhicule enregistré !</tr>}
</table>
<button onclick="location.href='@Url.Action("Add", "Vehicle")'" style="background-color:transparent; border-color:transparent;"><img src="~/Content/image/icons8-people-in-car-side-view-filled-50.png" /><br />Ajouter un véhicule</button>